[package]
name = "system_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
file_tools = {path = "../file_tools"}
whoami = {version = "1.2.1"}
chrono = {version = "0.4.19"}