[package]
name = "matlab_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#matfile = {version = "0.3.1"}
system_tools = {path = "../system_tools"}
