[default]
keep_alive = 5
temp_dir = "/tmp"
cli_colors = true

[debug]
address = "0.0.0.0"
port = 8020
workers = 4
keep_alive = 0
log_level = "normal"
temp_dir = "/tmp"

[release]
address = "0.0.0.0"
port = 8100
workers = 12
keep_alive = 5
log_level = "critical"
temp_dir = "/tmp"
