function modelrateV5(mmscore,testnum)
%fuction to score model data to modal data
% bagdata is 3x3 matrix: co,hc,no and 3 bag values each
% modaldata is recorded modal data for CO,HC,NO (n,3) matrix
% COtp,HCtp,NOtp are vectors of cumulative tailpipe values
%Number of phases

        %mmscore: n x 9 matrix. 
        %cold start score, bag 3 score, combined score(line match+bag123)
        %aveCOcold,CObagacc(3,1),COscore,aveHCcold,...
        %HCbagacc(3,1),HCscore,aveNOcold,NObagacc(3,1),NOscore];
     
        
    aveCOcold = mmscore(testnum, 1);%cold start score
    CObagacc = mmscore(testnum, 2);%bag 3 score
    COscore = mmscore(testnum, 3);%combined score(line match+bag123)
    aveHCcold = mmscore(testnum, 4);
    HCbagacc = mmscore(testnum, 5);
    HCscore = mmscore(testnum, 6);
    aveNOcold = mmscore(testnum, 7);
    NObagacc = mmscore(testnum, 8);
    NOscore = mmscore(testnum, 9);
    
 %DISPLAY------------------------   
    %display dialog box 
    d = figure('Position',[500 500 400 300],...%[left,bottom,width,height]
        'Name',['Model Match Score: ',num2str(testnum)]);
                        

    %display scores on dialog box
    %CO scores
    CO1 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 240 210 40],...
               'String',['CO cold start score ',num2str(aveCOcold)]);
    CObag3 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 220 210 40],...
               'String',['CO bag3 score ',num2str(CObagacc)]);
    CO2 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 200 210 40],...
               'String',['CO score ',num2str(COscore)]);
           
    %HC scores      
    HC1 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 180 210 40],...
               'String',['HC cold start score: ', num2str(aveHCcold)]);
           
    HCbag3 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 160 210 40],...
               'String',['HC bag3 score: ', num2str(HCbagacc)]);
    HC2 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 140 210 40],...
               'String',['HC score: ', num2str(HCscore)]);
           
    %NO scores
    NO1 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 120 210 40],...
               'String',['NO cold start score: ', num2str(aveNOcold)]);
           
    NObag3 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 100 210 40],...
               'String',['NO cold start score: ', num2str(NObagacc)]);
           
    NO2 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 80 210 40],...
               'String',['NO score: ', num2str(NOscore)]);
           
    %consolidated score
    txt4 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 50 210 40],...
               'String',['Overall score: ', num2str(COscore+HCscore+NOscore)]);
           
    %model match color scheme 
    %CO color scheme
    if     COscore <30
            COcolor = [.2 1 .2];
            COtext = 'Good Match';
    elseif COscore < 50
            COcolor = [1 1 .2];
            COtext = 'ok Match';
    else
            COcolor = [1 .2 .2];
            COtext = 'poor Match';
    end
    %HC color scheme
    if     HCscore <30
            HCcolor = [.2 1 .2];
            HCtext = 'Good Match';
    elseif HCscore < 50
            HCcolor = [1 1 .2];
            HCtext = 'ok Match';
    else
            HCcolor = [1 .2 .2];
            HCtext = 'poor Match';
    end
    %NO color scheme
    if     NOscore < 40
            NOcolor = [.2 1 .2];
            NOtext = 'Good Match';
    elseif NOscore < 70
            NOcolor = [1 1 .2];
            NOtext = 'ok Match';
    else
            NOcolor = [1 .2 .2];
            NOtext = 'poor Match';
    end
    %CO match color button
    CObtn = uicontrol('Parent',d,...
               'Style','togglebutton',...
               'String',COtext,...
               'BackgroundColor',COcolor,...
               'Position',[200 250 70 30]);
    %HC match color button
    HCbtn = uicontrol('Parent',d,...
               'Style','togglebutton',...
               'String',HCtext,...
               'BackgroundColor',HCcolor,...
               'Position',[200 190 70 30]);
    %NO match color button
    NObtn = uicontrol('Parent',d,...
               'Style','togglebutton',...
               'String',NOtext,...
               'BackgroundColor',NOcolor,...
               'Position',[200 130 70 30]);
%close button
    btn1 = uicontrol('Parent',d,...
               'Position',[20 20 160 25],...
               'String','Close',...
               'Callback','delete(gcf)');
   
end
    


